trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'Build_and_Test'
    jobs:
      - job: Build
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              workingDirectory: 'src'
      - job: 'Unit_Test' #Place holder for any unit tests
      - job: 'Service_Test'
        steps:
          - task: DockerCompose@0
            inputs:
              containerregistrytype: 'Container Registry'
              currentWorkingDirectory: '$(Build.SourcesDirectory)'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Run a Docker Compose command'
              abortOnContainerExit: true
              dockerComposeCommand: 'up --exit-code-from service_tests'
              arguments: ''