version: "3.8"
services:

  db:
    image: postgres:latest
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: 12345678

  azure-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
      - 10001:10001
    entrypoint:
      - azurite-blob
      - --loose
      - --blobHost
      - 0.0.0.0
      - -l
      - /tmp
      - -d
      - /tmp/debug.log

  api:
    build:
      context: .
      dockerfile: WebApi.Dockerfile
    ports: 
      - 57893:57893
    environment: 
      "EnvVars_ConnectionStrings:db": "User ID=postgres;Password=12345678;Host=db;Port=5432;Database=Expenses"
      "EnvVars_ConnectionStrings:storage": "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-blob-storage:10000/devstoreaccount1;"
    depends_on: 
      - db
      - azure-blob-storage
    restart: on-failure
  
  service_tests:
    build:
      context: .
      dockerfile: ServiceTests.Dockerfile
    environment: 
      "EnvVars_webapi_url": "http://api:57893"
    depends_on: 
      - api
